jobs:
  - name: data-cleaning
    __tracker_experiment_name: Mlflow-tracker
    stages:
      - name: "clean-base-tables"
        tasks:
          - name: "product"
            params: {}
          - name: "orders"
            params: {}

      - name: "clean-derivative-tables"
        tasks:
          - name: "sales"
            params: {}
      - name: "train-test-split"
        tasks:
          - name: "train-test"
            params:
              target: unit_price
              test_size: 0.2

  - name: feat-engg
    __tracker_experiment_name: Mlflow-tracker
    stages:
      - name: "feature-pipelines"
        tasks:
          - name: "transform-features"
            params:
              outliers:
                method: mean
                drop: False
              sampling_fraction: 0.1

  - name: model-gen
    __tracker_experiment_name: Mlflow-tracker
    stages:
      - name: "model-creation"
        tasks:
          - name: "train-model"
            params:
              sampling_fraction: 0.1

  - name: model-eval
    __tracker_experiment_name: Mlflow-tracker
    stages:
      - name: "model-predict"
        tasks:
          - name: "score-model"
            params: {}